# syntax=docker/dockerfile:1
FROM nvidia/cuda:10.1-base-ubuntu16.04
LABEL Description="MgNet Docker build"

ARG CONDA_PYTHON_VERSION=3
ARG CONDA_DIR=/opt/conda

# Instal basic utilities
RUN apt-get update && \
    apt-get -y --no-install-recommends install \
    git wget unzip bzip2 sudo cmake vim build-essential ca-certificates libopencv-dev \
    gcc g++ make && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install miniconda
ENV PATH $CONDA_DIR/bin:$PATH
COPY ./packages/Miniconda3-py38_4.10.3-Linux-x86_64.sh /tmp/
RUN echo 'export PATH=$CONDA_DIR/bin:$PATH' > /etc/profile.d/conda.sh && \
    /bin/bash /tmp/Miniconda3-py38_4.10.3-Linux-x86_64.sh -b -p $CONDA_DIR && \
    rm -rf /tmp/*

# use root user
ENV HOME /root
SHELL ["/bin/bash", "-c"]

RUN conda install -c conda-forge conda-pack
ADD ./packages/packed_conda_base.tar.gz $CONDA_DIR/
RUN conda-unpack

# Install mamba to speed up Conda
# RUN conda install -y mamba -c conda-forge
# RUN mamba install -c acellera -c conda-forge htmd=1.13.10
# Copy the YAML file into Docker image, and then update the base/root Conda environment
# ADD ./packages/environment.yml /src/
# RUN conda env update --file ./environment.yml
# RUN mamba env update --file ./environment.yml && conda clean -tipy

# Copy local packages to /src/
COPY ./packages/mgltools_x86_64Linux2_1.5.6.tar.gz /src/
COPY ./packages/vmd-1.9.4a57.bin.LINUXAMD64-CUDA102-OptiX650-OSPRay185.opengl.tar.gz /src/
COPY ./packages/MgNet.tar.gz /src/

# Compile mgltools
RUN cd /src && \
    tar -xzf mgltools_x86_64Linux2_1.5.6.tar.gz && \
    cd ./mgltools_x86_64Linux2_1.5.6 && \
    ./install.sh && \
    rm -rf /src/mgltools_x86_64Linux2_1.5.6.tar.gz

# Compile vmd
RUN cd /src && \
    tar -xzf vmd-1.9.4a57.bin.LINUXAMD64-CUDA102-OptiX650-OSPRay185.opengl.tar.gz && \
    cd vmd-1.9.4a57 && \
    ./configure && \
    cd ./src && make install && \
    rm -rf /src/vmd-1.9.4a57.bin.LINUXAMD64-CUDA102-OptiX650-OSPRay185.opengl.tar.gz

# Compile MgNet
RUN cd /src && \
    tar -xzf MgNet.tar.gz && \
    cd MgNet && \
    /bin/bash install.sh && \
    rm -rf /src/MgNet.tar.gz

# Fix some HTMD issues
RUN sed -i '95 s/^/#/' /opt/conda/lib/python3.6/site-packages/htmd/latest.py
RUN sed -i '79,81 s/^/#/' /opt/conda/lib/python3.6/site-packages/htmdx/cli.py
# Supress conda module not found error
RUN sed -i '12,13 s/^/#/' /opt/conda/bin/conda
RUN echo "    pass" >> /opt/conda/bin/conda

# Set neccessary environment variables
ENV PATH=${PATH}:/usr/local/bin:/src/MgNet/bin

# For interactive shell
# RUN conda init bash
# RUN echo "conda activate base" >> /root/.bashrc
